### ISSUE TITLE
Add stats for transactions 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#1210]
### Problem

There are times when transactions fail with `INVALID_NODE_ACCOUNT_ID`, `TRANSACTION_EXPIRED`, or other errors where transactions do not succeed. In order to debug these transaction failures the SDK needs to provide some stats. 

### Solution

Log the transactions that were submitted in the last 30 minutes.

Stored locally and default is not enabled.

This should include:

- Transaction ID 
- Node the transaction was submitted to
- Network response (either the network error or success response)
- The network is was submitted to (mainnet, testnet, previewnet)

**Comment by nikola-genov** [comment]
In order to clean-up the logs every 30 minutes or so we need to have some background task that would be taking care of that. We think this should be out of the scope of the SDKs and it will be much more straightforward approach to have the user to enable/disable logging and then clean-up the logs if he wishes so.

We added some more logging to the base Executable class in addition to the already existing logging. To save the output to a file the user needs to setup slf4j properly. One option is to enable slf4j's simple logger:

 - in build.gradle change implementation 'org.slf4j:slf4j-api:2.0.5' to 'org.slf4j:slf4j-simple:2.0.3'
 - add a 'simplelogger.properties' file to the resources directory with the following contents:
      org.slf4j.simpleLogger.defaultLogLevel = trace
      org.slf4j.simpleLogger.logFile = /{path}/{logFileName}

Probably that should better documented in the official hedera documentation... @SimiHunjan, what are your thoughts?

**Comment by ochikov** [comment]
### Specifications and logger behaviour

- The default behaviour has to be ***OFF*** - no log statements if not explicitly set by the user
- The logger has to be able to be set on both client and transaction/query levels
    - If a logger is set for a specific transaction/query and the client also has a logger - we prioritize the one in the transaction/query
    - If a given transaction/query does not have a logger, we use the one from the client (if there is)

### Functionalities

- The logger api has to:
    - provide a way to change the level of the logger
    - provide a way to silence the logger (switch between on/off - meaning that if you switch it **off** and then turn it back ****on****, the level of the logger has to be the one before switching it to ******off****** in the first place
    - set/get methods for those fields
    - expose the logging methods of the library
        - currently the library used in JS SDK has the following log levels: *************trace, debug, info, warn, error, fatal*************

### Implementation **(*************suggestion from JS SDK**)***

- Create a *Logger* class which will basically encapsulate the logger library used in the SDK and expose necessary fields, methods, levels and so on
- Create a ********LogLevel******** class which will act as a mapping between the log levels from the library and levels in the SDK
- Create an example which will show the behaviour and all of the functionalities mentioned above

### What to log?

- Transaction ID
- Node Id and address of each transaction attempt
- When node is unhealthy
- Node the transaction was submitted to
- Network response (either the network error or success response)
- The network it was submitted to (mainnet, testnet, previewnet)
