### ISSUE TITLE
Bip39 passphrase must be normalized

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-sdk-java#1240]
Current implementation allows any unicode string as a passphrase, but the [BIP39 spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic) states that it must be normalized to NFKD 

Open for discussion: Should there be any additional limitations on the allowed passphrases? The above change will bring the SDK in line with the BIP39 spec, but it seems very common for wallets to limit the user to specifically ASCII characters, with a length cap of 100 characters. Should we follow suit, to avoid the situation where a user cannot recover a key on specific wallets?

**Comment by alittley** [comment]
In regards to choosing normalized unicode vs ascii: it's worth considering that unicode normalization isn't a trivial task. Java seems to have convenient functions for this, but C++ doesn't. IMO it would be hard to guarantee that normalization functions across all languages perform perfectly and deterministically for all edge cases... I understand now, having looked into the problem, why all wallets I've seen limit the user to ASCII only

@nikola-genov I see you've picked up this task - are you planning to normalize to NFKD, or limit to ASCII?

**Comment by nikola-genov** [comment]
@SimiHunjan , @alittley , I think in order to be BIP-39 compliant the SDK should allow unicode passphrase and simply NFKD normalize it. SDK consumers (3rd party apps and wallets) may decide to limit the user to ASCII-only pass on their end, but the SDK should not impose such restrictions. What are your thoughts?

**Comment by SimiHunjan** [comment]
@rbair23 @lbaird thoughts on this?

**Comment by alittley** [comment]
@nikola-genov I think this seems reasonable.

My one concern is whether we can be confident that various libraries have 100% correct *and* consistent normalization. Unicode is a wide standard...

**Comment by nikola-genov** [comment]
@alittley, this is a valid concern, however there's not much we can do about it - in order to be Bip39 compliant we must normalize. 

Another possible issue is if someone has already used unicode passphrase with the current sdk, once that change gets released he'll no longer be able to recover his private key unless downgrading to a legacy sdk version.

**Comment by ochikov** [comment]
I agree with @nikola-genov. If somebody has issues, he is going to downgrade and recover his passphrase.
