### ISSUE TITLE
Sporadic/inconsistent erroneous DUPLICATE_TRANSACTION errors in testnet.

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#130]
When submitting CryptoTransfers using async calls in rapid succession that differ only in memo (same sender/recipient/amount), I'm getting sporadic DUPLICATE_TRANSACTION results.
Sometimes they happen, sometimes they don't.

A modified examples TransferCrypto.java (edit SET_YOUR_RECIPIENT_ID_HERE):

```
package com.hedera.hashgraph.sdk.examples.advanced;

import com.hedera.hashgraph.sdk.HederaException;
import com.hedera.hashgraph.sdk.HederaThrowable;
import com.hedera.hashgraph.sdk.TransactionRecord;
import com.hedera.hashgraph.sdk.account.AccountId;
import com.hedera.hashgraph.sdk.account.CryptoTransferTransaction;
import com.hedera.hashgraph.sdk.examples.ExampleHelper;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

public final class TransferCrypto {
    private TransferCrypto() { }

    private static final int CONCURRENT_TRANSACTIONS = 10;

    public static void main(String[] args) throws HederaException, InterruptedException {
        var operatorId = ExampleHelper.getOperatorId();
        var client = ExampleHelper.createHederaClient();
        var recipientId = AccountId.fromString(SET_YOUR_RECIPIENT_ID_HERE);
        var amount = 1;

        var latch = new CountDownLatch(CONCURRENT_TRANSACTIONS);

        var senderBalanceBefore = client.getAccountBalance(operatorId);
        var receiptBalanceBefore = client.getAccountBalance(recipientId);
        System.out.println("" + operatorId + " balance = " + senderBalanceBefore + " , " +
                recipientId + " balance = " + receiptBalanceBefore);

        Consumer<TransactionRecord> onSuccess = (record) -> {
            System.out.println(System.currentTimeMillis() + " " + record.getMemo() + " completed " +
                record.getConsensusTimestamp());
            latch.countDown();
        };

        Consumer<HederaThrowable> onError = (e) -> {
            System.out.println(e);
            if (e instanceof HederaException) {
                var he = (HederaException)e;
                System.out.println(he.getMessage());
                System.out.println(he.responseCode);
                he.printStackTrace();
            }
            latch.countDown();
        };

        for (var i = 0; i < CONCURRENT_TRANSACTIONS; ++i) {
            var memo = "async-test-" + System.currentTimeMillis(); // i;
            var cryptoTransfer = new CryptoTransferTransaction(client)
                    .addSender(operatorId, amount)
                    .addRecipient(recipientId, amount)
                    .setMemo(memo);
            System.out.println(System.currentTimeMillis() + " " + memo + " sent.");
            cryptoTransfer.executeForRecordAsync(onSuccess, onError);
            Thread.sleep(5);
        }
        try {
            latch.await(20, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        var senderBalanceAfter = client.getAccountBalance(operatorId);
        var receiptBalanceAfter = client.getAccountBalance(recipientId);
        System.out.println("" + operatorId + " balance = " + senderBalanceAfter + " , " +
                recipientId + " balance = " + receiptBalanceAfter);
    }
}
```

Exceptions seen:

```
com.hedera.hashgraph.sdk.HederaException: DUPLICATE_TRANSACTION
DUPLICATE_TRANSACTION
DUPLICATE_TRANSACTION
com.hedera.hashgraph.sdk.HederaException: DUPLICATE_TRANSACTION
    at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:39)
    at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:173)
    at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:13)
    at com.hedera.hashgraph.sdk.HederaCall$1.onNext(HederaCall.java:40)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
    at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
    at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mike-burrage-hedera** [comment]
Using latest master 07d41ada0dd2cbe273bc5df75001fd85c99b3ed5 and testnet (the new one).

**Comment by abonander** [comment]
@mike-burrage-hedera this is almost certainly due to multiple transaction IDs being created with the same `validStartAt`; I would expect this to be the case if the minimum clock granularity of the system you're running this on is greater than 5ms, which is apparently the case on Windows (if that is the case then sleeping 5ms is probably meaningless as well and `Thread.sleep()` is probably returning immediately).

The Java clock API makes no guarantees about monotonicity, but we can wrap `java.time.Clock` ourselves to always return an instant that is at least 1 nanosecond ahead of the previous one. I don't know what clock granularity the network requires though.

**Comment by lbaird** [comment]
Yes, the clock should be wrapped so that every start time is at least 1 nanosecond later than the previous one.

That 1 nanosecond is enough to prevent the Hedera services from treating two transactions as duplicates. All the bits of the nanosecond field are treated as significant.


________________________________

**Comment by abonander** [comment]
Will do.

**Comment by bugbytesinc** [comment]
@mike-burrage-hedera I we had a very similar issue with the .net sdk and had solved it as you suggest above.  We haven't had that problem crop up since.

**Comment by mike-burrage-hedera** [comment]
@abonander that's not the case. In the example I provided, I print the system time just before making the async call, and they're all different.

**Comment by bugbytesinc** [comment]
@abonander but do you have control over when/how the SDK creates the transaction ID?  I've not read the code, but it seems plausible the SDK might create them all within the resolution of the system clock resulting in duplicate timestamps unless there is an explicit lock and check to check for that case.

**Comment by abonander** [comment]
Right now it's just referencing the system clock, yes. That's in the constructor of `TransactionId`: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java#L31

It's subtracting 10 seconds to make sure the `validStartAt` is in the past; this combined with clock adjustments and granularity issues could still be producing duplicate IDs.

**Comment by abonander** [comment]
So it is what I thought, but in a bit of a roundabout way:

* The actual transfer transaction isn't getting duplicate IDs, @mike-burrage-hedera you were right about that. However:
* Querying for a record requires a payment (correct?) which is automatically set in `QueryBuilder.toProto()` if not provided: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java#L31
* However, we query for the receipt first and wait for it to become known before issuing the record query: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Transaction.java#L233-L237
https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Transaction.java#L303-L333
* For some reason, `AsyncReceiptHandler` appears to be calling `onReceipt.accept()` multiple times in quick succession which is what's producing our duplicate transaction IDs because of the granularity issues we've been discussing. I'm getting this even on Linux because it seems that the clock granularity is 1 microsecond.

**Comment by mike-burrage-hedera** [comment]
I think it's when the cost gets added by the QueryBuilder.toProto().

 https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java#L41-42

grpc executor thread is serializing a bunch of requests in a row immediately (thus hitting the granularity issue).

**Comment by abonander** [comment]
Something like that, probably. I added prints in `TransactionBuilder.build()` and found that multiple payments were being constructed for each transfer but couldn't pin down why. I'm adding several mitigations:

* Only constructing one `TransactionRecordQuery` per `executeAsync` call
* Throwing `IllegalStateException` if `execute()` or `executeAsync()` is called more than once for a given `HederaCall` implementation
* Ensuring `Instant`s are at least always increasing
