### ISSUE TITLE
Transaction Fee default approach

### ISSUE THREAD

**Issue by kenthejr** [hashgraph/hedera-sdk-java#191]
It seems to me that there are a few ways to handle transaction fee defaults:

- hardcode a default fee and allow an override like we do now: https://github.com/hashgraph/hedera-sdk-java/blob/f144a5be42d5d67ebbaf57e49ad372fc9c2f4858/src/main/java/com/hedera/hashgraph/sdk/Client.java#L25
- set the default to null and require a developer to set the fee to something
- set the default to some really large number
- automatically set the fee based on some external query (checking w/ Hedera for the fee schedule)

The first approach can go out of sync with the fee schedule and occasionally result in an INSUFFICIENT_TX_FEE error for those who implement the default, but don't override.

The second approach defeats the purpose of defaults and just adds to the number of lines required to get a simple application up and running.

The third approach could lead to some surprises about costs, but it would guarantee success and a simple implementation.

Final request requires there to be a way to query a fee schedule.

**Comment by mike-burrage-hedera** [comment]
Another wrinkle is the fact that the implicit transactions created by the SDK _only_ use the default.

For example an AccountCreateTransaction's executeForRecord() generates a CryptoCreate transaction (utilizing the default if necessary) and a subsequent CryptoGetAccountRecords query (utilizing the default because the caller doesn't have a means of specifying explicitly for this _set_ of transactions).

I don't have a simple solution in mind - just bringing up the fact that every executeForRecord() implicitly authorizes an additional default fee to be taken.

As an aside - this will cause the caller's request to FAIL in the SDK if the CryptoGetAccountRecordsQuery fails even if the transaction itself succeeded.

**Comment by mike-burrage-hedera** [comment]
Adding another wrinkle is that every transaction that is executed as an executeForRecord() has an additional implicit GetTransactionRecord() call sent with the default maxFee set. This authorizes an additional maxFee by the caller, which may not be clear, and the caller has no control over it other than via the default (currently).

**Comment by abonander** [comment]
@kenthejr I believe if you set the transaction fee to greater than the account's balance it rejects the transaction so option 3 is probably not going to work in general unless we query the account balance on startup.

**Comment by abonander** [comment]
Ideally we could just calculate the fee but it requires the fee schedule as well as the code that uses that schedule to calculate the actual fee which would need to be provided by the Hedera engineering team; it appears there are a lot of magic numbers that go into the calculation.

**Comment by abonander** [comment]
We've decided for now that we're going to require manually specifying payments for everything until we figure out fee calculation, so we're going to deprecate `QueryBuilder.setPaymentDefault()` (with no parameter) and `TransactionBuilder.executeForRecord()` (because the user needs to specify a payment for the record query).

**Comment by paulmadsenhed** [comment]
there are two separate questions

1) a default for the value of a fee on a transaction. The client can safely set this high, as they will only be charged a lesser amount. The pricing tool gives them as estimate. Currently, the SDK provides no mechanism for clients to determine a reasonable value for this fee. It might be possible in the future for clients to either figure it out themselves (if they had access to the feeschedule) or ask a node (comparable to COST_ANSWER).  

2) a default for the transfer on a payment transaction for a query. Unlike the transaction fee above, there is no comparable safety net for the client for this value - nodes will process the full transfer value as they have no context as to the original query for which this is a payment. Conseqiently, a default is risky for the client because it implies over spending. Nodes can do a COST_ANSWER query to ask a node 'how much would this query cost if I actually asked for it?'. These COST_ANSWER queries are free (though currently nodes still expect to see a payment transaction with 0 transfer). The client takes the response to a COST_ANSWER query and uses it as the value of the transfer for the payment transaction for the real query they send next. Its unlikely that clients would be able to calculate this value (even if they had the feeschedule) because some query responses are open ended in the amount of bytes returned. eg GetFileContents.

**Comment by mehcode** [comment]
Defaults are now 1 hbar for both transactions and payments and can be configured via `setMaxTransactionFee` and `setMaxQueryPayment`
