### ISSUE TITLE
private constructor for classes such as "AccountInfo"

### ISSUE THREAD

**Issue by calvinchengx** [hashgraph/hedera-sdk-java#237]
*Problem*

Most of the SDK classes like `AccountInfo` have a private constructor by default. 

For instance, https://github.com/hashgraph/hedera-sdk-java/blob/41afc0f394a42061a9ac0f37327d60790ced0ceb/src/main/java/com/hedera/hashgraph/sdk/account/AccountInfo.java#L75

This prevents SDK users from sub-classing them and implement custom serializers (such as a custom serializer for the Key attribute).

**Comment by mehcode** [comment]
@calvinchengx I disagree on principle here. 

Classes, especially small data types like `AccountInfo`, should not be thought of as extension points unless otherwise documented. 

Reasons are detailed in "Effective Java" under "Item 18: Favor composition over inheritance" ( tried to find a good web reference but can't ). tldr; is composition leads to a far more flexible interface.

For your abstract use case, my recommendation would be to make a `MyAccountInfo` class that has a private member `AccountInfo` that's set in the constructor. 

---

I don't know your specific use case though. If you have a concrete proposal like all simple data types (like those returned from queries) should be setup that they are serializable using something like Jackson out-of-the-box I would probably agree with that.

**Comment by calvinchengx** [comment]
I agree that we shouldn't use inheritance; and use composition in preference.

But composition is a "has-a" relationship, which requires that `AccountInfo` be assignable as well. So composition won't work when trying to assign `AccountInfo` when it has a private constructor.

But the issue here isn't whether `AccountInfo` is extendable or composable; so, ignore my previous suggestion of making the constructor public.

The problem is - when using the SDK, we need to write an additional class just so that we can serialize the `Key` attribute in `AccountInfo`.  

This can probably be avoided if we simply support serialization within the SDK classes.

What do you think?

A possible example implementation here - https://github.com/hashgraph/hedera-cli/blob/1f581ebc18433d503e512b9cc693414b71b8811b/src/main/java/com/hedera/cli/models/AccountInfoSerializer.java

cc @enerestar

**Comment by abonander** [comment]
We can add support for Jackson using `jackson-annotations`, there's not much need to hand-roll a serializer.

**Comment by calvinchengx** [comment]
Is this in 0.8.1 ?

**Comment by abonander** [comment]
It would be `0.8.2`.

**Comment by calvinchengx** [comment]
Thanks for clarification. Looking forward to `0.8.2` then. And we can close this issue once we use JDK's serialization in `hedera-cli`.  That would be a far more elegant and simpler implementation.

**Comment by abonander** [comment]
Implementing `Serializable` is also straightforward.
