### ISSUE TITLE
Transaction: throw in getReceipt()/getRecord() if execute() was not called

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#268]
We introduced a new footgun by deprecating `.executeForReceipt()`: the user could forget to call `.execute()` entirely. `getReceipt()` will still wait ~5 minutes before throwing `UNKNOWN`.

**Comment by mehcode** [comment]
I'm thinking on this more and I still think we should get rid of `Transaction.getReceipt` and `Transaction.getRecord`. 

Here is the current state of master.

```java
// 1 - Build Transaction
Transaction tx = new AccountCreateTransaction()
  .setInitialBalance(100)
  .setKey(someNewPublicKey)
  .build(hederaClient);

// 2 - Execute Transaction
TransactionId id = tx.execute(hederaClient);

// 3 - Get Receipt (waits for consensus)
TransactionReceipt receipt = tx.getReceipt(hederaClient);
```

---

@abonander and I have discussed adding `TransactionId.getReceipt` as it seems to fit. That change would allow:

```java
// 1 - Build Transaction
Transaction tx = new AccountCreateTransaction()
  .setInitialBalance(100)
  .setKey(someNewPublicKey)
  .build(hederaClient);

// 2 - Execute Transaction
TransactionId id = tx.execute(hederaClient);

// 3 - Get Receipt (waits for consensus)
// [ still works ] TransactionReceipt receipt = tx.getReceipt(hederaClient);
TransactionReceipt receipt = id.getReceipt(hederaClient);
```

And because the return types flow nicely now, the following is now possible:

```java
TransactionReceipt receipt = new AccountCreateTransaction()
  .setInitialBalance(100)
  .setKey(someNewPublicKey)
  // 1 & 2 ( this is already possible ) - Build and execute transaction
  .execute(hederaClient)
  // 3 - Get Receipt (waits for consensus)
  .getReceipt(hederaClient);
```

---

Given that `TransactionId.getReceipt` seems like a massively good idea ( it pushes the usability back to what we had with `executeForReceipt` but it keeps the separate between executing and receipt fetching clear ); next, we need to ask if `Transaction.getReceipt` would ever be used enough to warrant their inclusion.

One potential foot-gun with `Transaction.getReceipt` is it can easily be called before you execute the transaction.

After this exercise I'm heavily leaning towards removing the methods. We can always _add_ methods if we find we need the short-cuts but its harder to remove them later on.
