### ISSUE TITLE
Display reason for `CONTRACT_REVERT_EXECUTED`

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#348]
Hi,

I have noticed that while EVM displays the reason when a modifier fails, Hedera doesn't and instead returns a generic 'CONTRACT_REVERT_EXECUTED". Is there a way to change this?

**Comment by mehcode** [comment]
@gregscullard Any ideas?

**Comment by czemelman** [comment]
@rahul-ki Could you be more specific. What is the exact case of revert where you able to see the reason in EVM and can not see in HH ? I know for example that if you have a require with error message the message would be returned back to you if require conditions are not answered

**Comment by czemelman** [comment]
@rahul-ki Please take a look at this transaction
https://app.dragonglass.me/hedera/transactions/00292661580382336303000000

It failed because one of the require conditions failed
If you look at contractCallResultsit has the following 
08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001864657669636520616c7265616479207265676973746572640000000000000000
This is your error message encoded as if Error(String) function would be called
Look at  this document for more info 
https://solidity.readthedocs.io/en/v0.6.2/control-structures.html
Just search for "08c379a"

**Comment by rahul-ki** [comment]
@czemelman 
I can actually confirm that it isn't a case. I just called invoked the following require statement:
```
require(msg.sender==owner, "caller is not owner of the smart contract");
```
I did indeed get CONTRACT_REVERT_EXECUTED, but on doing `error.getMessage()` I got nothing.

**Comment by czemelman** [comment]
@rahul-ki Can you send your transaction record or link to DragonGlass transaction ?

**Comment by mehcode** [comment]
> I can actually confirm that it isn't a case. I just called invoked the following require statement:

This looks like the fault of the SDK for not surfacing this to you. The data is definitely there in the network. I've seen it in the bytes in the TransactionRecord.

We could potentially notice `CONTRACT_REVERT_EXECUTED` and then pull the error details from the call result and surface that to the exception. That sounds very useful.

**Comment by rahul-ki** [comment]
@mehcode thanks! @czemelman my point was that in the event you send, I can not find out WHY the revert was executed.

**Comment by rahul-ki** [comment]
@mehcode was digging around in the SDK. Seems like the information never reaches the SDK and is "lost" in the protobuf. I assume we need to update that?

**Comment by mehcode** [comment]
The way the SDK is structured this is actually impossible. So we're going to instead allow you to turn off "throw on bad status" so you can inspect the record yourself. 

See https://github.com/hashgraph/hedera-sdk-java/issues/355
