### ISSUE TITLE
get uint16 from solidity contract call 

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#371]
No such method currently exists.

Also, as shown in the image why aren't the return types of various uints the same? They all can be long.

![image](https://user-images.githubusercontent.com/35169918/75444213-f163ce00-595a-11ea-80c2-15636883d0b7.png)

**Comment by abonander** [comment]
For now, you can use `(short) contractCallResult.getUint32(index)`.

We decided that it would be most intuitive if each method returned the equivalent Java integer width; yes they can all be `long` but with that argument `getUint8()` and `getUint32()` don't need to exist because we have `getUint64()`, you can use that plus a truncating cast to get any of the other integer types.

**Comment by lbaird** [comment]
So getUint32 is really acting like getInt32 (without the “U”)?  And for big positive integer answers, it returns a negative number?

Since Java doesn’t have a uint32, and we have to choose between returning either an int32 or int64, I would guess that users would prefer the latter.  Because it can at least represent all the possible values that could be returned. And the user is still free to cast it to a smaller bit size.

Or maybe not. I suppose I don’t know for sure what our users would prefer.


________________________________

**Comment by abonander** [comment]
We do note in the documentation that these methods are semantically redundant: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/contract/ContractFunctionResult.java#L185-L188

However, we thought we should have them because we were concerned that if someone was looking for methods specifically dealing with `uint` and couldn't find them, they might think the API doesn't support their use-case. Also, because we want API parity across languages where some of them _do_ support unsigned integers; Go being the foremost example of the languages we already support.

**Comment by lbaird** [comment]
That’s a good reason to provide a getUint32() function. But shouldn’t the getUint32() function return an int64?  Instead of an int32?  Because then it would always return an answer with the correct sign. (Of course, by int64 I mean Java long, and by int32 I mean Java int).

**Comment by abonander** [comment]
You probably didn't see my edits because you're replying by email. Java does have very basic support for unsigned arithmetic and comparison (which we point users to in the documentation):

* [Integer.compareUnsigned()](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#compareUnsigned-int-int-)
* [Integer.divideUnsigned()](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#divideUnsigned-int-int-)
* [Integer.remainderUnsigned()](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#remainderUnsigned-int-int-)
* [Integer.toUnsignedLong()](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#toUnsignedLong-int-)

My knowledge of two's complement arithmetic is a little rusty but I think addition, subtraction and multiplication function fine whether the value is signed or not.

If `getUint32()` returns a value widened to `long` (int64) then we're mostly just moving the problem to `getUint64()` which doesn't have a wider type than `long` to return.

**Comment by lbaird** [comment]
Those are good comments in the code about being signed. I agree that getUint64 has a problem that can’t be solved any other way, so the best we can do is put in those comments and force the user to be inconvenienced (such as when doing comparisons).  I was just suggesting that for 8, 16, or 32 bits, we could return 16, 32, or 64 bits (respectively), to make life easier for the user.  Then comparisons would work fine. And if they wanted to cast it smaller, they could.

But if you think users would prefer the smaller sizes, that’s fine.

**Comment by abonander** [comment]
Well, regardless, changing the existing methods to return wider types is a breaking change.

**Comment by lbaird** [comment]
Ok. Then better not to do it.

________________________________
