### ISSUE TITLE
File Transaction change name for .setContent ()

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#373]
It seems to me that:
When calling `FileAppendTransaction().setContent(content)` - you actually append the content to the file.
WHEREAS
When calling `FileUpdateTransaction().setContent(content)` - you actually replace all of the content of the file.

To prevent confusion, can
*  `FileAppendTransaction`'s `.setContent()` actually be called `.appendContent()` 
AND
* `FileUpdateTransaction()`'s `.setContent()` be called `.replaceContent()`

Thanks! This is a nomenclature issue more than anything else.

**Comment by abonander** [comment]
These map directly to the field name in the protobufs:

* https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/proto/FileAppend.proto#L14
* https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/proto/FileCreate.proto#L26

This doesn't seem to be a significant enough issue to justify deprecating the methods and replacing them with differently named ones. However, we could stand to document the methods for clarity's sake (which I made sure to do [when adding overloads that take `String](https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/file/FileAppendTransaction.java#L30) but forgot to go back and do for the originals).

**Comment by abonander** [comment]
`FileUpdateTransaction.addKey()` is actually a good example of where we probably will deprecate a method and replace it because of misleading naming: https://github.com/hashgraph/hedera-sdk-java/pull/380/files#diff-c16214ca3f6f586d0f84e75700af3b40R59-R72

We will probably be replacing it with `.setKeys()` which takes a `KeyList` and explicitly says it will replace the existing key list on the file.
