### ISSUE TITLE
SDK should sign transactions on demand

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-sdk-java#471]
By default, when executing a transaction, SDK picks 1/3 nodes to construct signed transaction with. Each of these transaction bytes is signed though in most cases only one is needed. Private key signing is resource intensive, we should optimize to sign the transactions on demand.

**Comment by mehcode** [comment]
- [ ] `Client.setOperatorPersistent(true)` that will mark the operator as **persistent**, meaning that its always there and we can sign on-demand instead of needing to sign up front

 - [ ] When using `Client.setOperator`, default `operatorPersistent` to `true`, otherwise `false`.

---

cc @danielakhterov

**Comment by danielakhterov** [comment]
This change should affect more than just the operator @mehcode. Perhaps we have `Transaction.sign[With|WithOperator]Persistent()` and/or `Transaction.persistantSigning(true)` which is `true` by default?
